---
- name: Add docker GPG apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }}/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  become: true

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/{{ ansible_system | lower}}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: true
  become: true
  register: dockerrepo

- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - containerd.io
    state: latest
  become: true

- name: Add {{ ansible_user }} to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true
  become: true
  register: dockergroup

# yes you really need to reboot on group change, since Ansible
# connects over an SSH session, it's the most
# sure-fire way to ensure permissions take effect
# for something like docker that runs as a service.
- name: reboot
  ansible.builtin.reboot:
    msg: "Ansible reboot - docker role"
  become: true
  when:
    - dockergroup.changed
    - inventory_hostname != "localhost"
